# Generated by Django 4.2 on 2024-08-05 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('age', models.IntegerField(default=1)),
                ('country', models.CharField(max_length=30)),
                ('picture', models.ImageField(upload_to='artist_images')),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('year', models.DateField()),
                ('gender', models.CharField(choices=[('R', 'Rock'), ('R', 'Reggaeton'), ('S', 'Salsa'), ('P', 'Pop'), ('B', 'Balada'), ('C', 'Clasico'), ('V', 'Vallenato'), ('M', 'Merengue')], max_length=30)),
                ('picture', models.ImageField(upload_to='album_images')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='album_manager.artist')),
            ],
        ),
    ]
